name: my workflow
on:
  workflow_dispatch:
  push:

jobs:
 job1:
  runs-on: ubuntu-latest
  steps:
   - name: hello world
     run: echo "hello,world!"
 job2:
  runs-on: ubuntu-latest
  steps:
   - name: failed step
     run: |
       echo "i will fail"
       exit0
   - name: say goodbye
     run: |
      echo "goodbye!"
      exit1
      
     
    
   
   
